name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: self-hosted

    variables:
      DEPLOY_PATH: /apps/aennesia/backend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./packages/backend
        run: npm i

      - name: Build
        working-directory: ./packages/backend
        run: npm run build

      - name: Deploy - remove old version
        run: find $DEPLOY_PATH -mindepth 1 ! -regex '^$DEPLOY_PATH/node_modules\(/.*\)?' -delete

      - name: Deploy - copy sources
        working-directory: ./packages/backend
        run: cp -r dist/* $DEPLOY_PATH

      - name: Deploy - copy package.json
        working-directory: ./packages/backend
        run: cp package.json $DEPLOY_PATH

      - name: Deploy - Install dependencies
        working-directory: $DEPLOY_PATH
        run: npm i --omit=dev

      - name: Deploy - Restart server
        working-directory: /apps/aennesia
        run: pm2 restart aennesia.ecosystem.config.js
